import { InstrumentsData } from "../../types/instruments";

export const sampleData: InstrumentsData[] = [
  {
    instrumentId: 1,
    instrumentName: 'Armstrong - Jacobi',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 2,
    instrumentName: 'Armstrong - Reichert',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 3,
    instrumentName: 'Armstrong Sporer and Nikolaus',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 4,
    instrumentName: 'Auer - Bailey',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 5,
    instrumentName: 'Bailey - Rosenbaum',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 6,
    instrumentName: 'Bartoletti Group',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 7,
    instrumentName: 'Barton - Stark',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 8,
    instrumentName: 'Batz - Reichert',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 9,
    instrumentName: 'Batz - Ziemann',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 10,
    instrumentName: 'Batz Schimmel and Kessler',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 11,
    instrumentName: 'Baumbach Inc',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 12,
    instrumentName: 'Bayer and Sons',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 13,
    instrumentName: 'Beahan - Cartwright',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 14,
    instrumentName: 'Beatty - Boyle',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 15,
    instrumentName: 'Beer Christiansen and Von',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 16,
    instrumentName: 'Beier and Sons',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 17,
    instrumentName: 'Bergnaum Veum and Strosin',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 18,
    instrumentName: 'Blick - Bogisich',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 19,
    instrumentName: 'Bode - Cartwright',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 20,
    instrumentName: 'Bogan - Deckow',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 21,
    instrumentName: 'Bosco Inc',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 22,
    instrumentName: 'Boyer - Ritchie',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 23,
    instrumentName: 'Boyer Ebert and MacGyver',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 24,
    instrumentName: 'Braun - Effertz',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 25,
    instrumentName: 'Carroll - Heathcote',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 26,
    instrumentName: 'Carroll Group',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 27,
    instrumentName: 'Carter - Terry',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 28,
    instrumentName: 'Cartwright - Larkin',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 29,
    instrumentName: 'Casper Inc',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 30,
    instrumentName: 'Cassin Reichel and Cummings',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 31,
    instrumentName: 'Champlin - Sawayn',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 32,
    instrumentName: 'Cole - Lueilwitz',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 33,
    instrumentName: 'Connelly Inc',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 34,
    instrumentName: 'Conroy Marvin and Lind',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 35,
    instrumentName: 'Corkery Group',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 36,
    instrumentName: 'Corkery Schoen and Dietrich',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 37,
    instrumentName: 'Corwin - Hane',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 38,
    instrumentName: 'Crooks Gislason and Olson',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 39,
    instrumentName: 'Cruickshank - Spencer',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 40,
    instrumentName: 'Cummerata Group',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 41,
    instrumentName: 'Dare Mitchell and Borer',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 42,
    instrumentName: 'Dickens - Turcotte',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 43,
    instrumentName: 'Dickens Lowe and Bradtke',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 44,
    instrumentName: 'Dietrich Heller and Hodkiewicz',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 45,
    instrumentName: 'Donnelly Carter and Medhurst',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 46,
    instrumentName: 'Douglas - Runte',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 47,
    instrumentName: 'Douglas Harvey and Fritsch',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 48,
    instrumentName: 'Emard LLC',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 49,
    instrumentName: 'Emmerich Witting and Considine',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 50,
    instrumentName: 'Ernser Mayer and Reynolds',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'US',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 51,
    instrumentName: 'Farrell and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 52,
    instrumentName: 'Feil - Heathcote',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 53,
    instrumentName: 'Gerlach and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 54,
    instrumentName: 'Gerlach Abbott and Altenwerth',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 55,
    instrumentName: 'Gibson Beahan and Cremin',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: false,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2022-09-15 00:00:00',
    notes: 'Private Equity; Industrials; Non Tradable Instrument',
  },
  {
    instrumentId: 56,
    instrumentName: 'Gibson Schamberger and Champlin',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 57,
    instrumentName: 'Gislason and Sons',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 58,
    instrumentName: 'Glover LLC',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 59,
    instrumentName: 'Goodwin - Metz',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 60,
    instrumentName: 'Greenfelder - Feest',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 61,
    instrumentName: 'Greenholt - Ritchie',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 62,
    instrumentName: 'Greenholt LLC',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 63,
    instrumentName: 'Grimes Collins and Ward',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 64,
    instrumentName: 'Gulgowski and Sons',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 65,
    instrumentName: 'Gusikowski Inc',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 66,
    instrumentName: 'Haag LLC',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 67,
    instrumentName: 'Hackett Inc',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: false,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2022-09-15 00:00:00',
    notes: 'Private Equity; Consumer Staples; Non Tradable Instrument',
  },
  {
    instrumentId: 68,
    instrumentName: 'Haley LLC',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 69,
    instrumentName: 'Hamill Zemlak and Rosenbaum',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 70,
    instrumentName: 'Hand - Volkman',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 71,
    instrumentName: 'Hansen - Mosciski',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 72,
    instrumentName: 'Harber Dibbert and Hagenes',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 73,
    instrumentName: 'Heathcote - Parisian',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 74,
    instrumentName: 'Hermiston Hane and Crona',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 75,
    instrumentName: 'Herzog Huel and Lockman',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 76,
    instrumentName: 'Hettinger Group',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 77,
    instrumentName: 'Hickle and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 78,
    instrumentName: 'Hickle LLC',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 79,
    instrumentName: 'Hills Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 80,
    instrumentName: 'Hilpert Kuhic and Gerlach',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 81,
    instrumentName: 'Howe - Zieme',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 82,
    instrumentName: 'Huels Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 83,
    instrumentName: 'Jacobi Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 84,
    instrumentName: 'Jacobs Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 85,
    instrumentName: "Jacobson - O'Reilly",
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 86,
    instrumentName: 'Jacobson - Rempel',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 87,
    instrumentName: 'Jakubowski and Sons',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 88,
    instrumentName: 'Jakubowski Frami and Gibson',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 89,
    instrumentName: 'Johns and Sons',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 90,
    instrumentName: 'Jones Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 91,
    instrumentName: 'Keebler Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 92,
    instrumentName: 'Kessler Farrell and Gislason',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 93,
    instrumentName: 'Kirlin and Sons',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 94,
    instrumentName: 'Kling - Will',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 95,
    instrumentName: 'Koepp and Sons',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 96,
    instrumentName: 'Koepp Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 97,
    instrumentName: 'Konopelski - Gusikowski',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 98,
    instrumentName: 'Kshlerin McKenzie and Kulas',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 99,
    instrumentName: 'Kuhic - Dibbert',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 100,
    instrumentName: 'Kuhlman and Sons',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'CN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 101,
    instrumentName: 'Langworth - Hills',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 102,
    instrumentName: 'Leannon Mann and Mitchell',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 103,
    instrumentName: 'Legros - Hane',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 104,
    instrumentName: 'Legros Wisoky and Von',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 105,
    instrumentName: 'Lehner and Sons',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 106,
    instrumentName: 'Lesch - Harber',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 107,
    instrumentName: 'Lind - Leannon',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 108,
    instrumentName: 'Little Inc',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 109,
    instrumentName: 'Lowe - Skiles',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 110,
    instrumentName: 'Lynch Aufderhar and Hansen',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 111,
    instrumentName: 'MacGyver and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 112,
    instrumentName: 'Mann LLC',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 113,
    instrumentName: 'Mante Inc',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 114,
    instrumentName: 'Marks Nitzsche and Kirlin',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 115,
    instrumentName: 'Marvin - Hodkiewicz',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 116,
    instrumentName: 'Marvin - Price',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 117,
    instrumentName: 'McCullough Medhurst and Wuckert',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 118,
    instrumentName: 'Medhurst Wilderman and Murray',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 119,
    instrumentName: 'Mitchell Lebsack and Zboncak',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 120,
    instrumentName: 'Mohr and Sons',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 121,
    instrumentName: 'Mohr Dooley and Metz',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 122,
    instrumentName: 'Morissette Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 123,
    instrumentName: 'Mosciski - Hintz',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 124,
    instrumentName: 'Mosciski Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 125,
    instrumentName: 'Mosciski Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 126,
    instrumentName: 'Mraz Hackett and Ziemann',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 127,
    instrumentName: 'Nader - Kirlin',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 128,
    instrumentName: 'Nikolaus Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 129,
    instrumentName: 'Nolan Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 130,
    instrumentName: 'Nolan Koepp and Ankunding',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'GB',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 131,
    instrumentName: "O'Connell - Koelpin",
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 132,
    instrumentName: "O'Reilly - Powlowski",
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 133,
    instrumentName: 'Padberg - Lakin',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 134,
    instrumentName: 'Parisian LLC',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 135,
    instrumentName: 'Pfannerstill Bode and Runte',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 136,
    instrumentName: 'Pollich - Stroman',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 137,
    instrumentName: 'Pouros Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 138,
    instrumentName: 'Predovic - Kling',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 139,
    instrumentName: 'Price - Cremin',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 140,
    instrumentName: 'Prohaska - Block',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'AU',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 141,
    instrumentName: 'Prosacco Murazik and Baumbach',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 142,
    instrumentName: 'Purdy Group',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 143,
    instrumentName: 'Purdy LLC',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 144,
    instrumentName: 'Raynor Group',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 145,
    instrumentName: 'Reinger Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 146,
    instrumentName: 'Robel - Hickle',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 147,
    instrumentName: 'Rodriguez Reichert and Nolan',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 148,
    instrumentName: 'Romaguera Batz and Watsica',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 149,
    instrumentName: 'Runolfsdottir Group',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 150,
    instrumentName: 'Runolfsson - Prohaska',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'IN',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 151,
    instrumentName: 'Runte Lubowitz and Schultz',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 152,
    instrumentName: 'Sanford Tremblay and Wunsch',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 153,
    instrumentName: 'Schmeler - Zieme',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 154,
    instrumentName: 'Schneider Group',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 155,
    instrumentName: 'Schoen Goyette and Kohler',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 156,
    instrumentName: 'Schroeder Aufderhar and Lynch',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 157,
    instrumentName: 'Schulist Inc',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 158,
    instrumentName: 'Schumm Hirthe and Ryan',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 159,
    instrumentName: 'Shields Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 160,
    instrumentName: 'Shields LLC',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 161,
    instrumentName: 'Sipes Inc',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 162,
    instrumentName: 'Sipes Vandervort and Kerluke',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 163,
    instrumentName: 'Skiles - Murazik',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 164,
    instrumentName: 'Skiles Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 165,
    instrumentName: 'Spinka - Maggio',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 166,
    instrumentName: 'Stanton Friesen and Simonis',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 167,
    instrumentName: 'Steuber - Kiehn',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 168,
    instrumentName: 'Stiedemann Group',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 169,
    instrumentName: 'Stoltenberg - Nienow',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 170,
    instrumentName: 'Streich Inc',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'BR',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 171,
    instrumentName: 'Swaniawski and Sons',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 172,
    instrumentName: 'Swaniawski Brakus and Hahn',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 173,
    instrumentName: 'Thiel - Douglas',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 174,
    instrumentName: 'Thiel - Labadie',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 175,
    instrumentName: 'Thiel Prosacco and Ferry',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 176,
    instrumentName: 'Thompson - Hills',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 177,
    instrumentName: 'Thompson and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 178,
    instrumentName: 'Tillman Hickle and Jakubowski',
    instrumentType: 'Real Estate',
    sector: 'Real Estate',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Real Estate; Real Estate; Tradable Instrument',
  },
  {
    instrumentId: 179,
    instrumentName: 'Toy - Paucek',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 180,
    instrumentName: 'Toy - VonRueden',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 181,
    instrumentName: 'Trantow - Smith',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 182,
    instrumentName: 'Turner Rath and Luettgen',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 183,
    instrumentName: 'Ullrich LLC',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 184,
    instrumentName: 'Vandervort Inc',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 185,
    instrumentName: 'Vandervort Okuneva and Carroll',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 186,
    instrumentName: 'Veum LLC',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 187,
    instrumentName: 'Volkman Haag and Schiller',
    instrumentType: 'Private Equity',
    sector: 'Industrials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Industrials; Tradable Instrument',
  },
  {
    instrumentId: 188,
    instrumentName: 'Von - Kunde',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 189,
    instrumentName: 'Walsh and Sons',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 190,
    instrumentName: 'Weber Kohler and Kautzer',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'JP',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 191,
    instrumentName: 'Wilderman Huel and Sporer',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 192,
    instrumentName: 'Will - Quigley',
    instrumentType: 'Private Equity',
    sector: 'Energy',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Energy; Tradable Instrument',
  },
  {
    instrumentId: 193,
    instrumentName: 'Wisoky - Gleason',
    instrumentType: 'Private Equity',
    sector: 'Information Technology',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Information Technology; Tradable Instrument',
  },
  {
    instrumentId: 194,
    instrumentName: 'Wisoky and Sons',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 195,
    instrumentName: 'Wisoky Inc',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 196,
    instrumentName: 'Wyman - Kling',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
  {
    instrumentId: 197,
    instrumentName: 'Wyman Mohr and Johns',
    instrumentType: 'Private Equity',
    sector: 'Communication Services',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Communication Services; Tradable Instrument',
  },
  {
    instrumentId: 198,
    instrumentName: 'Yost LLC',
    instrumentType: 'Private Equity',
    sector: 'Financials',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Financials; Tradable Instrument',
  },
  {
    instrumentId: 199,
    instrumentName: 'Yundt - Macejkovic',
    instrumentType: 'Private Equity',
    sector: 'Consumer Staples',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Consumer Staples; Tradable Instrument',
  },
  {
    instrumentId: 200,
    instrumentName: 'Zieme - West',
    instrumentType: 'Private Equity',
    sector: 'Healthcare',
    country: 'DE',
    instrumentCurrency: 'USD',
    isTradeable: true,
    createdAt: '2019-02-01 00:00:00',
    modifiedAt: '2019-02-01 00:00:00',
    notes: 'Private Equity; Healthcare; Tradable Instrument',
  },
]
